package TAS;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.ZonedDateTime;
import java.util.Date;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Session2_1 {

	public static void main(String[] args) throws InterruptedException, IOException { 
		
        System.setProperty("webdriver.chrome.driver","C:\\Users\\usw38n0\\Documents\\Selenium\\chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        
        // Wait until elements on the page are loaded before next action
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
		
        // Define target URL
		String appUrl = "https://mail.google.com";
				
		//
		System.out.println("Open Chrome to " + appUrl + " ...");
		
		// launch the browser and open the application url 
		driver.get(appUrl);
		
		// 2 sec pause
		System.out.println("2 sec timeout after URL is opened...");				
		Thread.sleep(2000);
		
		// maximize the browser window if necessary 
		// driver.manage().window().maximize(); 
		
		// =============================
		// Page Title Validation Section
		// =============================
		// declare and initialize the variable to store the expected title of the webpage. 
		String expectedTitle = "Gmail"; 
		// fetch the title of the web page and save it into a string variable 
		String actualTitle = driver.getTitle();
		
		// compare the expected title of the page with the actual title of the page and print the result 
		if (expectedTitle.equals(actualTitle)) 
		{ 
			System.out.println("Verification Successful - The correct title is displayed on the web page."); 
			} 
		else 
		{ 
			System.out.println("Verification Failed - An incorrect title is displayed on the web page. Actual Title = " + actualTitle); 
			}
		
		// =============
		// Login Section
		// =============
		
		// enter a valid username in the email textbox 
		WebElement username = driver.findElement(By.id("identifierId"));
		username.clear(); 
		username.sendKeys("XXXX");

		Thread.sleep(2000);
		
		// click on the Next button 
		driver.findElement(By.id("identifierNext")).click();
		
		Thread.sleep(2000);
		
		// enter a valid password in the password textbox
		WebElement password = driver.findElement(By.xpath("//*[@id=\"password\"]/div[1]/div/div[1]/input"));
		password.clear(); 
		password.sendKeys("XXXX"); 
		
		Thread.sleep(2000);
		
		driver.findElement(By.id("passwordNext")).click();
		System.out.println("Login successfully.... ");
		
		Thread.sleep(5000);
		
		// =====================
		// Compose Email Section
		// =====================
				
		String strFN="vj";
		String strLN="raggy";
		String strEmail="Vjraggy@yahoo.com";
     
        System.out.println(" First:" + strFN + ", Last:" + strLN + ", Email:"+ strEmail);
        
        System.out.println("Click on COMPOSE...");
		driver.findElement(By.xpath("//*[contains(text(),'COMPOSE')]")).click();
		
		Thread.sleep(5000);
		
		System.out.println("Fill in To.... ");
		driver.findElement(By.xpath("//textarea[@name='to']")).sendKeys("vjraggy@gmail.com");
		
		Thread.sleep(1000);
        
		System.out.println("Fill in Subject.... " );
        driver.findElement(By.xpath("//input[@name='subjectbox']")).sendKeys(" Selenium Script: " 
        		+ strFN + " " + strLN + " " + strEmail); 
        
        Thread.sleep(1000);
        
        String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new Date());
        
        System.out.println("Fill in Message Body.... ");
        driver.findElement(By.xpath("//div[@aria-label='Message Body']")).sendKeys(" Message Body: \n\nThis is the test email sent to test the selenium script @ "
        		+ timeStamp
        		+ "\nThis email is generated by automated script\r\r"
        		+ "\nThis will be deleted after\n\n\n"
        		+ ZonedDateTime.now());
        
        Thread.sleep(1000);
        
        System.out.println("Click on Send.... " + timeStamp);
        
        driver.switchTo().defaultContent();
        
        driver.findElement(By.xpath("//div[text()='Send']")).click();
        
		Thread.sleep(2000);
		
		// =================
		// End, Refresh and Reload a page
		// =================
				
		System.out.println("Refresh.... ");
		Thread.sleep(2000);
		driver.navigate().refresh();
		
		System.out.println("End of the Script.... ");
	
	} 
}
